#:kivy 1.8.0
Analysis:
    name: 'ab_13'
    img13: screen13_img
    next1_13: next1_13

    Image:
        source: 'app_data/butt_up.png'
        size_hint: 0.5, 0.075
        pos_hint: {'center_x': 0.5, 'center_y': 0.95}
        keep_ratio: False
        allow_stretch: True

    Image:
        source: 'app_data/butt_down.png'
        size_hint: 0.6, 0.075
        pos_hint: {'center_x': 0.5, 'center_y': 0.875}
        keep_ratio: False
        allow_stretch: True

    Label:
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0.341, 0.392, 1, 1
        size_hint: .1, .1
        pos_hint: {'center_x': 0.95, 'center_y': 0.95}
        text:'A I M S'

    Button:
        size_hint: 0.15, 0.1
        pos_hint: {'center_x': 0.3, 'center_y': 0.775}
        text: 'Choose Color 1'
        background_down: 'app_data/butt_down.png'
        background_normal: 'app_data/butt_up.png'
        color: (0, 0.033, 0.329, 1)
        border: (0, 0, 0, 0)
        on_release:
            root.show_gradWheel1()

    Button:
        size_hint: 0.15, 0.1
        pos_hint: {'center_x': 0.5, 'center_y': 0.775}
        text: 'Choose Color 2'
        background_down: 'app_data/butt_down.png'
        background_normal: 'app_data/butt_up.png'
        color: (0, 0.033, 0.329, 1)
        border: (0, 0, 0, 0)
        on_release:
            root.show_gradWheel2()

    Button:
        size_hint: 0.15, 0.1
        pos_hint: {'center_x': 0.7, 'center_y': 0.775}
        text: 'Default Colors'
        background_down: 'app_data/butt_down.png'
        background_normal: 'app_data/butt_up.png'
        color: (0, 0.033, 0.329, 1)
        border: (0, 0, 0, 0)
        on_release:
            root.reset_gradColor()

    Label:
        size_hint_y: None
        pos_hint: {'center_x': 0.5, 'center_y': 0.95}
        height: '32dp'
        text: 'Step13 - Visualize Amino Acid Frequencies'
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0, 0.033, 0.329, 1

    Label:
        size_hint_y: None
        pos_hint: {'center_x': 0.5, 'center_y': 0.875}
        height: '32dp'
        text: 'A Simple Difference in AA Frequency Between Groups'
        font_name: 'app_data/Poppins-Medium.ttf'

    Image:
        id: screen13_img
        size_hint: 0.75, 0.75
        pos_hint: {'center_x': 0.5, 'center_y': 0.45}
        source: 'app_data/white.png'
        keep_ratio: True

    Button:
        size_hint: 0.15, 0.1
        pos_hint: {'center_x': 0.5, 'center_y': 0.1}
        text: 'Get Frequency'
        background_down: 'app_data/butt_down.png'
        background_normal: 'app_data/butt_up.png'
        color: (0, 0.033, 0.329, 1)
        border: (0, 0, 0, 0)
        on_release:
            root.get_freq()
            screen13_img.reload()

    Button:
        id: prev1_13
        size_hint: 0.15, 0.1
        text: '< Go Back'
        color: (0.341, 0.392, 1, 1)
        background_normal: 'app_data/transparent.png'
        background_down: 'app_data/transparent.png'
        background_color: (0.773, 0.784, 0.796, 1)
        pos_hint: {'center_x': 0.15, 'center_y': 0.1}
        on_release: 
            app.go_prev_screen(num = 12)

    Button:
        id: next1_13
        size_hint: 0.15, 0.1
        text: 'Next >'
        background_normal: 'app_data/transparent.png'
        background_down: 'app_data/transparent.png'
        pos_hint: {'center_x': 0.85, 'center_y': 0.1}
        color: (0.341, 0.392, 1, 1)
        background_color: (0.773, 0.784, 0.796, 1)
        disabled: True
        on_release: 
            app.go_next_screen( num = 14 )