#:kivy 1.8.0
Root:
    name: 'mhc_1'
    next1_1: next1_1
    lessF: lessF

    Label:
        size_hint: .1, .1
        pos_hint: {'center_x': 0.5, 'center_y': 0.95}
        text:'Step1 - Loading Files (MHC Version)'

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.5, 'center_y': 0.85}
        text:'Two FASTA Files Required, Additional Files Optional'

    ################## K now to the next page. This is not great, but it is pretty
    Button:
        id: next1_1
        size_hint: None, None
        size: '150dp', '48dp'
        text: 'Next'
        pos_hint: {'center_x': 0.85, 'center_y': 0.1}
        disabled: True
        on_release: 
            app.go_next_screen(num = 2)

    Button:
        id: next1.3
        size_hint: None, None
        size: '150dp', '48dp'
        text: 'Previous'
        pos_hint: {'center_x': 0.15, 'center_y': 0.1}
        on_release: 
            root.reset_loadScrn()
            app.go_main_screen(num = 0)

    Button:
        id: next1.2
        size_hint: None, None
        size: '150dp', '48dp'
        text: 'Add More FASTAs'
        pos_hint: {'center_x': 0.4, 'center_y': 0.1}
        on_release: root.more_fastas()

    Button:
        id: lessF
        size_hint: None, None
        size: '150dp', '48dp'
        text: 'Remove FASTAs'
        pos_hint: {'center_x': 0.6, 'center_y': 0.1}
        disabled: True
        on_release: root.less_fastas()