#:kivy 1.8.0
Analysis:
    name: 'mhc_11'
    img11: screen11_img

    Image:
        source: 'app_data/butt_up.png'
        size: '450dp','25dp'
        size_hint: None, None
        pos_hint: {'center_x': 0.5, 'center_y': 0.95}
        keep_ratio: False
        allow_stretch: True

    Image:
        source: 'app_data/butt_down.png'
        size: '425dp','25dp'
        size_hint: None, None
        pos_hint: {'center_x': 0.5, 'center_y': 0.875}
        keep_ratio: False
        allow_stretch: True

    Label:
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0.341, 0.392, 1, 1
        size_hint: .1, .1
        pos_hint: {'center_x': 0.95, 'center_y': 0.95}
        text:'A I M S'

    Label:
        size_hint_y: None
        pos_hint: {'center_x': 0.5, 'center_y': 0.95}
        height: '32dp'
        text: 'Step11 - Visualize Amino Acid Frequencies'
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0, 0.033, 0.329, 1

    Label:
        size_hint_y: None
        pos_hint: {'center_x': 0.5, 'center_y': 0.875}
        height: '32dp'
        text: 'A simple difference in AA frequency between groups'
        font_name: 'app_data/Poppins-Medium.ttf'

    Image:
        id: screen11_img
        size: '750dp','750dp'
        size_hint: None, None
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        source: 'app_data/white.png'

    Button:
        size_hint: None, None
        size: '150dp', '48dp'
        pos_hint: {'center_x': 0.5, 'center_y': 0.1}
        text: 'Get Frequency'
        background_down: 'app_data/butt_down.png'
        background_normal: 'app_data/butt_up.png'
        color: (0, 0.033, 0.329, 1)
        border: (0, 0, 0, 0)
        on_release:
            root.get_freq()
            screen11_img.reload()

    Button:
        id: next1.3
        size_hint: None, None
        size: '150dp', '48dp'
        text: '< Go Back'
        color: (0.341, 0.392, 1, 1)
        background_normal: 'app_data/transparent.png'
        background_down: 'app_data/transparent.png'
        background_color: (0.773, 0.784, 0.796, 1)
        pos_hint: {'center_x': 0.15, 'center_y': 0.1}
        on_release: 
            app.go_prev_screen(num = 10)