#:kivy 1.8.0
aligner_gen:
    name: 'pep_2'
    input1: input1
    degen_drop: degen_drop
    lenCut: lenCut
    bulger: bulger

    Image:
        source: 'app_data/butt_up.png'
        size_hint: 0.5, 0.075
        pos_hint: {'center_x': 0.5, 'center_y': 0.95}
        keep_ratio: False
        allow_stretch: True

    Label:
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0.341, 0.392, 1, 1
        size_hint: .1, .1
        pos_hint: {'center_x': 0.95, 'center_y': 0.95}
        text:'A I M S'
    
    Image:
        source: 'app_data/square_background.png'
        size_hint: 0.95, 0.325
        pos_hint: {'center_x': 0.505, 'center_y': 0.76}
        keep_ratio: False
        allow_stretch: True

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.5, 'center_y': 0.95}
        height: '32dp'
        text:'Step2 - Parse and Annotate Dataset'
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0, 0.033, 0.329, 1

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.5, 'center_y': 0.85}
        height: '32dp'
        text:'Rename input files (if desired) and define output directory'
        font_name: 'app_data/Poppins-Medium.ttf'

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.5, 'center_y': 0.80}
        height: '32dp'
        text:'Check the documentation for proper formatting of input files.'
        font_name: 'app_data/Poppins-Medium.ttf'
    
    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.2, 'center_y': 0.725}
        height: '32dp'
        text:'Output Folder Name:'
        font_name: 'app_data/Poppins-Medium.ttf'

    CTextInput:
        id: input1
        size_hint: 0.5,None
        write_tab: False
        pos_hint: {'center_x': 0.6, 'center_y': 0.725}
        height: '32dp'
        multiline: False
        text: 'new_folder'

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.5, 'center_y': 0.6}
        height: '32dp'
        color: 0.341, 0.392, 1, 1
        text:'Below, input labels for the data loaded in on the previous screen:'
        font_name: 'app_data/Poppins-Medium.ttf'

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.25, 'center_y': 0.3}
        height: '32dp'
        text:'Select a length cutoff for peptides'
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0.341, 0.392, 1, 1

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.25, 'center_y': 0.25}
        height: '32dp'
        text:'(set > 100 if you want to include all lengths):'
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0.341, 0.392, 1, 1

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.25, 'center_y': 0.2}
        height: '32dp'
        text:'Length Cutoff:'
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0.341, 0.392, 1, 1

    CTextInput:
        id: lenCut
        size_hint: 0.05,0.05
        write_tab: False
        pos_hint: {'center_x': 0.35, 'center_y': 0.2}
        height: '32dp'
        multiline: False
        text: '15'

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.75, 'center_y': 0.3}
        height: '32dp'
        text:'Select a "bulge" padding for encoding'
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0.341, 0.392, 1, 1

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.75, 'center_y': 0.25}
        height: '32dp'
        text:'(see documentation for further detail):'
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0.341, 0.392, 1, 1

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.55, 'center_y': 0.2}
        height: '32dp'
        text:'Bulge Pad:'
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0.341, 0.392, 1, 1

    CTextInput:
        id: bulger
        size_hint: 0.05,0.05
        write_tab: False
        pos_hint: {'center_x': 0.65, 'center_y': 0.2}
        height: '32dp'
        multiline: False
        text: '6'

    # Need to have an extra section to drop degenerate loops:
    CheckBox:
        id: degen_drop
        size_hint: 0.15, 0.1
        state: 'down'
        pos_hint: {'center_x': 0.65, 'center_y': 0.1}

    Label:
        size_hint: None , None
        pos_hint: {'center_x': 0.45, 'center_y': 0.1}
        height: '32dp'
        text:'Drop Duplicated Peptides:'
        font_name: 'app_data/Poppins-Medium.ttf'
        color: 0.341, 0.392, 1, 1


    ####################### END FASTA DESIGNATIONS ############################
    Button:
        id: next1.3
        size_hint: 0.15, 0.1
        text: 'Next >'
        background_normal: 'app_data/transparent.png'
        background_down: 'app_data/transparent.png'
        pos_hint: {'center_x': 0.85, 'center_y': 0.1}
        color: (0.341, 0.392, 1, 1)
        background_color: (0.773, 0.784, 0.796, 1)
        on_release: 
            root.make_path()
            root.check_aligns()
            app.go_next_screen(num = 3)

    Button:
        id: next1.3
        size_hint: 0.15, 0.1
        text: '< Go Back'
        color: (0.341, 0.392, 1, 1)
        background_normal: 'app_data/transparent.png'
        background_down: 'app_data/transparent.png'
        background_color: (0.773, 0.784, 0.796, 1)
        pos_hint: {'center_x': 0.15, 'center_y': 0.1}
        on_release: 
            app.go_prev_screen(num = 1)